name: CI

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --verbose

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Check current version
        id: current_version
        run: echo "VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: Check if version is already published
        id: check_published
        run: |
          if cargo search --limit 1 $(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name') | grep -q "$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')"; then
            echo "PUBLISHED=true" >> $GITHUB_OUTPUT
          else
            echo "PUBLISHED=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        if: steps.check_published.outputs.PUBLISHED == 'true'
        run: cargo set-version --bump patch

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --no-verify
